### PR TITLE
fix: extract AtOnboardingResetResult enum to at_onboarding_reset_resu…

### LINKED ISSUE #507: at_onboarding_reset_screen.dart need to be imported to access AtOnboardingResetResult enum
### Which at_widget package you find issue with?

at_onboarding_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

at_onboarding_flutter: 5.0.0

### What happened?

I need to `import 'package:at_onboarding_flutter/screen/at_onboarding_reset_screen.dart';` to access the `AtOnboardingResetResult` enum.

I think the `AtOnboardingResetResult` enum should be in it's own file so it can be imported as `import 'package:at_onboarding_flutter/at_onboarding_reset_result.dart';` or `import 'package:at_onboarding_flutter/at_onboarding_flutter.dart';`

### Steps to reproduce

```bash
1. import 'package:at_onboarding_flutter/at_onboarding_flutter.dart'

3. Create a variable `var a = AtOnboardingResetResult.success;` and you'll get an undefined name error.
...
```

### Additional info

_No response_

### Relevant log output

_No response_

### Flutter analyze output

_No response_

### Flutter doctor output

_No response_

### PR DESCRIPTION
**Pull request by HamdaanAliQuatil**
Closes #507 

**- What I did**

Extract AtOnboardingResetResult to at_onboarding_reset_result.dart

**- How I did it**

- [x] Created ```at_onboarding_reset_result.dart``` under lib/screens/ and placed ```AtOnboardingResetResult``` in the file.
- [x] imported ```at_onboarding_reset_result.dart```  in ```at_onboarding_reset_screen.dart```.
- [x] Imported  ```at_onboarding_reset_result.dart```  in ```at_onboarding.dart```.

**- Description for the changelog**

extract AtOnboardingResetResult to at_onboarding_reset_result.dart

### CODE REVIEW

File: packages/at_onboarding_flutter/lib/screen/at_onboarding_reset_result.dart [hunk 1]
```diff
@@ -0,0 +1,4 @@
+enum AtOnboardingResetResult {
+  cancelled,
+  success,
+}
```
Comment (sachins-geekyants) [inline packages/at_onboarding_flutter/lib/screen/at_onboarding_reset_result.dart]: @HamdaanAliQuatil screen may not be the right folder to keep **AtOnboardingResetResult**.
Can we move `AtOnboardingResetResult ` in `at_onboarding_result.dart` file ?

Comment (HamdaanAliQuatil) [reply packages/at_onboarding_flutter/lib/screen/at_onboarding_reset_result.dart]: Moved `AtOnboardingResetResult` to `at_onboarding_result.dart` and fixed required imports

**Review by sachins-geekyants — APPROVED** [review]
